DROP USER TECH_AND_SOLVE CASCADE;
CREATE USER V IDENTIFIED BY "Asdf1234" DEFAULT TABLESPACE "USERS";
grant CREATE session to TECH_AND_SOLVE;
grant CREATE TABLE to TECH_AND_SOLVE;
GRANT CREATE SEQUENCE TO TECH_AND_SOLVE;  
GRANT CREATE PROCEDURE TO TECH_AND_SOLVE;  
GRANT CREATE VIEW TO TECH_AND_SOLVE; 

ALTER USER TECH_AND_SOLVE quota unlimited ON "USERS";
ALTER database DEFAULT tablespace users;
COMMIT;
CREATE TABLE "TECH_AND_SOLVE".RE_MUDANZAS 
(
  "ID_MUDANZA" NUMBER(38,0) NOT NULL, 
  "TEST_CASE" VARCHAR2(100 BYTE) NOT NULL, 
  "USUARIOCREACION" VARCHAR2(20 BYTE) NOT NULL, 
  "FECHA_EJECUCION" DATE
);


ALTER TABLE "TECH_AND_SOLVE".RE_MUDANZAS ADD CONSTRAINT "PK_RE_MUDANZAS" PRIMARY KEY ("ID_MUDANZA");
CREATE SEQUENCE "TECH_AND_SOLVE".RE_MUDANZAS  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;